#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; 
    then
        SWITCHTO="-dark"

        #set the xfce theme
        xfconf-query -c xsettings -p /Net/ThemeName -s "Dracula"
        xfconf-query -c xsettings -p /Net/IconThemeName -s "Dracula"

        #set the GTK theme
        gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
        gsettings set org.gnome.desktop.interface icon-theme "Dracula"
    else

        #set the xfce theme
        xfconf-query -c xsettings -p /Net/ThemeName -s "Adawaita"
        xfconf-query -c xsettings -p /Net/IconThemeName -s "Fluent"

        #set the GTK theme
        gsettings set org.gnome.desktop.interface gtk-theme "Adawaita"
        gsettings set org.gnome.desktop.interface icon-theme "Fluent"

fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css


#change the background image and be cool about it ;)
swww img ~/.config/hypr/wallpaper$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2

#update the sddm image
ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#restart the waybar
killall -SIGUSR2 waybar
